from .other_cabs import OtherCabListSerializer, OtherCabWriteSerializer, OtherDriverReadserializer, OtherDriverWriteSerializer, OtherVehicleReadserializer,OtherVehicleWriteSerializer
from .vehicle import VehicleReadSerializer, VehicleWriteSerializer
from .bank import BankReadSerializer, BankWriteSerializer, BankBalanceReadSerializer, BankBalanceWriteSerializer
from .workshop import WorkshopReadSerializer, WorkshopWriteSerializer, MaintenanceReadSerializer, MaintenanceWriteSerializer
from .booking import BookingReadSerializer,BookingWriteSerializer
from .betta import BettaReadSerializer, BettaWriteSerializer
from .trip import TripReadSerializer,TripWriteSerializer
