from .other_cabs import OtherCabListSerializer, OtherCabWriteSerializer, OtherDriverReadserializer, OtherDriverWriteSerializer, OtherVechileReadserializer,OtherVechileWriteSerializer
from .vechile import VechileReadSerializer, VechileWriteSerializer
from .bank import BankReadSerializer, BankWriteSerializer, BankBalanceReadSerializer, BankBalanceWriteSerializer
