from .user import UserSerializer,RegisterSerializer,LoginSerializer,StaffSerializer,DriverSerializer

from .staff_list import StaffReadSerializer,DriverReadSerializer,UserReadSerializer,StaffWriteSerializer