from .other_cabs import OtherCabsListViewSet, OtherCabsCUDViewSet, OtherDriverListViewSet, OtherDriverCUDViewSet, OtherVechileListViewSet, OtherVechileCUDViewSet
from .vechile import VechileListViewSet, VechileCUDViewSet
from .bank import BankListViewSet, BankCUDViewSet, BankBalanceListViewSet,BankBalanceCUDViewSet
from .workshop import WorkshopListViewSet, WorkshopCUDViewSet, MaintenanceListViewSet, MaintenanceCUDViewSet
from .booking import BookingCUDAPIView,BookingListAPIView