from .other_cabs import OtherCabsListViewSet, OtherCabsCUDViewSet, OtherDriverListViewSet, OtherDriverCUDViewSet, OtherVechileListViewSet, OtherVechileCUDViewSet
from .vechile import VechileListViewSet, VechileCUDViewSet
